### ISSUE TITLE
Numpy issue on MacOS 11.2

### ISSUE THREAD

**Issue by dmitrym0** [Uzay-G/espial#5]
Running the second python command results in the following error. I was not able to resolve it by myself by downgrading numpy to 1.20.0:

```
~/w/g/espial ❯❯❯ python -m spacy download en_core_web_md                                                                   

Traceback (most recent call last):
  File "/Users/dmitry/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/dmitry/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/dmitry/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/dmitry/.pyenv/versions/3.9.4/lib/python3.9/site-packages/spacy/__init__.py", line 11, in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
  File "/Users/dmitry/.pyenv/versions/3.9.4/lib/python3.9/site-packages/thinc/api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "/Users/dmitry/.pyenv/versions/3.9.4/lib/python3.9/site-packages/thinc/initializers.py", line 4, in <module>
    from .backends import Ops
  File "/Users/dmitry/.pyenv/versions/3.9.4/lib/python3.9/site-packages/thinc/backends/__init__.py", line 8, in <module>
    from .cupy_ops import CupyOps, has_cupy
  File "/Users/dmitry/.pyenv/versions/3.9.4/lib/python3.9/site-packages/thinc/backends/cupy_ops.py", line 19, in <module>
    from .numpy_ops import NumpyOps
  File "thinc/backends/numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

```
~/w/g/espial ❯❯❯ python -V      
Python 3.9.4
```

**Comment by Uzay-G** [comment]
What version of Numpy does it say you have (`pip show numpy`)

**Comment by dmitrym0** [comment]
```
~ ❯❯❯ pip show numpy
Name: numpy
Version: 1.20.0
```


It works fine when I downgraded to python 3.7 🤷

**Comment by Uzay-G** [comment]
Hmm that's weird. I'll close this for now since it's more of an issue with Spacy it seems.

**Comment by Uzay-G** [comment]
@dmitrym0 how did Espial work for you? Do you have any feedback? Just made it public so there's rough patches but I'm curious to hear what you think.

**Comment by dmitrym0** [comment]
> @dmitrym0 how did Espial work for you? Do you have any feedback? Just made it public so there's rough patches but I'm curious to hear what you think.

@Uzay-G I gave it a quick try; my notes corpus is in org-mode, so I couldn't find an easy way to integrate the output markdown into org. I'll give it another go shortly though. Thanks for creating this, I think it has a lot of promise.
